# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /cygdrive/c/Users/Laur/AppData/Roaming/SPB_Data/texteditor

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /cygdrive/c/Users/Laur/AppData/Roaming/SPB_Data/texteditor

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/Laur/AppData/Roaming/SPB_Data/texteditor/CMakeFiles /cygdrive/c/Users/Laur/AppData/Roaming/SPB_Data/texteditor/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /cygdrive/c/Users/Laur/AppData/Roaming/SPB_Data/texteditor/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TextEditor

# Build rule for target.
TextEditor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextEditor
.PHONY : TextEditor

# fast build rule for target.
TextEditor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/build
.PHONY : TextEditor/fast

#=============================================================================
# Target rules for targets named TextEditor_autogen

# Build rule for target.
TextEditor_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 TextEditor_autogen
.PHONY : TextEditor_autogen

# fast build rule for target.
TextEditor_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor_autogen.dir/build.make CMakeFiles/TextEditor_autogen.dir/build
.PHONY : TextEditor_autogen/fast

InsertText.o: InsertText.cpp.o

.PHONY : InsertText.o

# target to build an object file
InsertText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/InsertText.cpp.o
.PHONY : InsertText.cpp.o

InsertText.i: InsertText.cpp.i

.PHONY : InsertText.i

# target to preprocess a source file
InsertText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/InsertText.cpp.i
.PHONY : InsertText.cpp.i

InsertText.s: InsertText.cpp.s

.PHONY : InsertText.s

# target to generate assembly for a file
InsertText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/InsertText.cpp.s
.PHONY : InsertText.cpp.s

ModifyText.o: ModifyText.cpp.o

.PHONY : ModifyText.o

# target to build an object file
ModifyText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/ModifyText.cpp.o
.PHONY : ModifyText.cpp.o

ModifyText.i: ModifyText.cpp.i

.PHONY : ModifyText.i

# target to preprocess a source file
ModifyText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/ModifyText.cpp.i
.PHONY : ModifyText.cpp.i

ModifyText.s: ModifyText.cpp.s

.PHONY : ModifyText.s

# target to generate assembly for a file
ModifyText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/ModifyText.cpp.s
.PHONY : ModifyText.cpp.s

PunctuationMark.o: PunctuationMark.cpp.o

.PHONY : PunctuationMark.o

# target to build an object file
PunctuationMark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/PunctuationMark.cpp.o
.PHONY : PunctuationMark.cpp.o

PunctuationMark.i: PunctuationMark.cpp.i

.PHONY : PunctuationMark.i

# target to preprocess a source file
PunctuationMark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/PunctuationMark.cpp.i
.PHONY : PunctuationMark.cpp.i

PunctuationMark.s: PunctuationMark.cpp.s

.PHONY : PunctuationMark.s

# target to generate assembly for a file
PunctuationMark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/PunctuationMark.cpp.s
.PHONY : PunctuationMark.cpp.s

StringManipulator.o: StringManipulator.cpp.o

.PHONY : StringManipulator.o

# target to build an object file
StringManipulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/StringManipulator.cpp.o
.PHONY : StringManipulator.cpp.o

StringManipulator.i: StringManipulator.cpp.i

.PHONY : StringManipulator.i

# target to preprocess a source file
StringManipulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/StringManipulator.cpp.i
.PHONY : StringManipulator.cpp.i

StringManipulator.s: StringManipulator.cpp.s

.PHONY : StringManipulator.s

# target to generate assembly for a file
StringManipulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/StringManipulator.cpp.s
.PHONY : StringManipulator.cpp.s

TextEditor_autogen/mocs_compilation.o: TextEditor_autogen/mocs_compilation.cpp.o

.PHONY : TextEditor_autogen/mocs_compilation.o

# target to build an object file
TextEditor_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/TextEditor_autogen/mocs_compilation.cpp.o
.PHONY : TextEditor_autogen/mocs_compilation.cpp.o

TextEditor_autogen/mocs_compilation.i: TextEditor_autogen/mocs_compilation.cpp.i

.PHONY : TextEditor_autogen/mocs_compilation.i

# target to preprocess a source file
TextEditor_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/TextEditor_autogen/mocs_compilation.cpp.i
.PHONY : TextEditor_autogen/mocs_compilation.cpp.i

TextEditor_autogen/mocs_compilation.s: TextEditor_autogen/mocs_compilation.cpp.s

.PHONY : TextEditor_autogen/mocs_compilation.s

# target to generate assembly for a file
TextEditor_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/TextEditor_autogen/mocs_compilation.cpp.s
.PHONY : TextEditor_autogen/mocs_compilation.cpp.s

TextHighLight.o: TextHighLight.cpp.o

.PHONY : TextHighLight.o

# target to build an object file
TextHighLight.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/TextHighLight.cpp.o
.PHONY : TextHighLight.cpp.o

TextHighLight.i: TextHighLight.cpp.i

.PHONY : TextHighLight.i

# target to preprocess a source file
TextHighLight.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/TextHighLight.cpp.i
.PHONY : TextHighLight.cpp.i

TextHighLight.s: TextHighLight.cpp.s

.PHONY : TextHighLight.s

# target to generate assembly for a file
TextHighLight.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/TextHighLight.cpp.s
.PHONY : TextHighLight.cpp.s

Utils.o: Utils.cpp.o

.PHONY : Utils.o

# target to build an object file
Utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/Utils.cpp.o
.PHONY : Utils.cpp.o

Utils.i: Utils.cpp.i

.PHONY : Utils.i

# target to preprocess a source file
Utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/Utils.cpp.i
.PHONY : Utils.cpp.i

Utils.s: Utils.cpp.s

.PHONY : Utils.s

# target to generate assembly for a file
Utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/Utils.cpp.s
.PHONY : Utils.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/TextEditor.dir/build.make CMakeFiles/TextEditor.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... TextEditor_autogen"
	@echo "... TextEditor"
	@echo "... InsertText.o"
	@echo "... InsertText.i"
	@echo "... InsertText.s"
	@echo "... ModifyText.o"
	@echo "... ModifyText.i"
	@echo "... ModifyText.s"
	@echo "... PunctuationMark.o"
	@echo "... PunctuationMark.i"
	@echo "... PunctuationMark.s"
	@echo "... StringManipulator.o"
	@echo "... StringManipulator.i"
	@echo "... StringManipulator.s"
	@echo "... TextEditor_autogen/mocs_compilation.o"
	@echo "... TextEditor_autogen/mocs_compilation.i"
	@echo "... TextEditor_autogen/mocs_compilation.s"
	@echo "... TextHighLight.o"
	@echo "... TextHighLight.i"
	@echo "... TextHighLight.s"
	@echo "... Utils.o"
	@echo "... Utils.i"
	@echo "... Utils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

